[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Jamie Hall <hello@jamiehall.eu>"]
edition = "2021"

[dependencies]
anyhow = "1.0.51"
colored = "2.0.0"
itertools = "0.10.1"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
